CREATE DATABASE peliculas_db;

USE peliculas_db;

CREATE TABLE Peliculas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255),
    anio INT,
    director VARCHAR(255),
    actor_principal VARCHAR(255),
    actor_secundario VARCHAR(255),
    genero VARCHAR(255)
);


INSERT INTO Peliculas (titulo, anio, director, actor_principal, actor_secundario, genero) VALUES
('Inception', 2010, 'Christopher Nolan', 'Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Sci-Fi'),
('The Dark Knight', 2008, 'Christopher Nolan', 'Christian Bale', 'Heath Ledger', 'Action'),
('Interstellar', 2014, 'Christopher Nolan', 'Matthew McConaughey', 'Anne Hathaway', 'Sci-Fi'),
('The Matrix', 1999, 'Lana Wachowski', 'Keanu Reeves', 'Laurence Fishburne', 'Sci-Fi'),
('The Godfather', 1972, 'Francis Ford Coppola', 'Marlon Brando', 'Al Pacino', 'Crime'),
('Pulp Fiction', 1994, 'Quentin Tarantino', 'John Travolta', 'Samuel L. Jackson', 'Crime'),
('Fight Club', 1999, 'David Fincher', 'Brad Pitt', 'Edward Norton', 'Drama'),
('Forrest Gump', 1994, 'Robert Zemeckis', 'Tom Hanks', 'Robin Wright', 'Drama'),
('The Shawshank Redemption', 1994, 'Frank Darabont', 'Tim Robbins', 'Morgan Freeman', 'Drama'),
('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Peter Jackson', 'Elijah Wood', 'Ian McKellen', 'Fantasy'),
('The Lord of the Rings: The Two Towers', 2002, 'Peter Jackson', 'Elijah Wood', 'Ian McKellen', 'Fantasy'),
('The Lord of the Rings: The Return of the King', 2003, 'Peter Jackson', 'Elijah Wood', 'Ian McKellen', 'Fantasy'),
('Star Wars: Episode IV - A New Hope', 1977, 'George Lucas', 'Mark Hamill', 'Harrison Ford', 'Sci-Fi'),
('Star Wars: Episode V - The Empire Strikes Back', 1980, 'Irvin Kershner', 'Mark Hamill', 'Harrison Ford', 'Sci-Fi'),
('Star Wars: Episode VI - Return of the Jedi', 1983, 'Richard Marquand', 'Mark Hamill', 'Harrison Ford', 'Sci-Fi'),
('The Silence of the Lambs', 1991, 'Jonathan Demme', 'Jodie Foster', 'Anthony Hopkins', 'Thriller'),
('Se7en', 1995, 'David Fincher', 'Brad Pitt', 'Morgan Freeman', 'Thriller'),
('Gladiator', 2000, 'Ridley Scott', 'Russell Crowe', 'Joaquin Phoenix', 'Action'),
('Saving Private Ryan', 1998, 'Steven Spielberg', 'Tom Hanks', 'Matt Damon', 'War'),
('The Departed', 2006, 'Martin Scorsese', 'Leonardo DiCaprio', 'Matt Damon', 'Crime'),
('Titanic', 1997, 'James Cameron', 'Leonardo DiCaprio', 'Kate Winslet', 'Romance'),
('Jurassic Park', 1993, 'Steven Spielberg', 'Sam Neill', 'Laura Dern', 'Sci-Fi'),
('The Lion King', 1994, 'Roger Allers', 'Matthew Broderick', 'Jeremy Irons', 'Animation'),
('Braveheart', 1995, 'Mel Gibson', 'Mel Gibson', 'Sophie Marceau', 'History'),
('Terminator 2: Judgment Day', 1991, 'James Cameron', 'Arnold Schwarzenegger', 'Linda Hamilton', 'Sci-Fi'),
('Back to the Future', 1985, 'Robert Zemeckis', 'Michael J. Fox', 'Christopher Lloyd', 'Sci-Fi'),
('Avatar', 2009, 'James Cameron', 'Sam Worthington', 'Zoe Saldana', 'Sci-Fi'),
('The Green Mile', 1999, 'Frank Darabont', 'Tom Hanks', 'Michael Clarke Duncan', 'Drama'),
('Toy Story', 1995, 'John Lasseter', 'Tom Hanks', 'Tim Allen', 'Animation'),
('The Lion King', 2019, 'Jon Favreau', 'Donald Glover', 'Beyoncé', 'Animation'),
('Frozen', 2013, 'Chris Buck', 'Kristen Bell', 'Idina Menzel', 'Animation'),
('The Avengers', 2012, 'Joss Whedon', 'Robert Downey Jr.', 'Chris Evans', 'Action'),
('Iron Man', 2008, 'Jon Favreau', 'Robert Downey Jr.', 'Gwyneth Paltrow', 'Action'),
('The Great Gatsby', 2013, 'Baz Luhrmann', 'Leonardo DiCaprio', 'Tobey Maguire', 'Drama'),
('The Notebook', 2004, 'Nick Cassavetes', 'Ryan Gosling', 'Rachel McAdams', 'Romance'),
('Shutter Island', 2010, 'Martin Scorsese', 'Leonardo DiCaprio', 'Mark Ruffalo', 'Thriller'),
('A Beautiful Mind', 2001, 'Ron Howard', 'Russell Crowe', 'Jennifer Connelly', 'Drama'),
('The Prestige', 2006, 'Christopher Nolan', 'Christian Bale', 'Hugh Jackman', 'Mystery'),
('Memento', 2000, 'Christopher Nolan', 'Guy Pearce', 'Carrie-Anne Moss', 'Mystery'),
('The Wolf of Wall Street', 2013, 'Martin Scorsese', 'Leonardo DiCaprio', 'Jonah Hill', 'Biography'),
('Catch Me If You Can', 2002, 'Steven Spielberg', 'Leonardo DiCaprio', 'Tom Hanks', 'Biography'),
('The Social Network', 2010, 'David Fincher', 'Jesse Eisenberg', 'Andrew Garfield', 'Biography'),
('Whiplash', 2014, 'Damien Chazelle', 'Miles Teller', 'J.K. Simmons', 'Drama'),
('Black Swan', 2010, 'Darren Aronofsky', 'Natalie Portman', 'Mila Kunis', 'Drama'),
('La La Land', 2016, 'Damien Chazelle', 'Ryan Gosling', 'Emma Stone', 'Romance'),
('Mad Max: Fury Road', 2015, 'George Miller', 'Tom Hardy', 'Charlize Theron', 'Action'),
('The Revenant', 2015, 'Alejandro G. Iñárritu', 'Leonardo DiCaprio', 'Tom Hardy', 'Adventure'),
('Gravity', 2013, 'Alfonso Cuarón', 'Sandra Bullock', 'George Clooney', 'Sci-Fi');
